{% set name = "flask-appbuilder" %}
{% set version = "4.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Flask-AppBuilder-{{ version }}.tar.gz
  sha256: a2242386a7f77df7020654b4d546a9dbac105058d2cd058b7fd9b1db457c2f32

build:
  noarch: python
  entry_points:
    - fabmanager = flask_appbuilder.console:cli
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools

  run:
    - python >=3.7
    - apispec >=6.0.0,<7
    - colorama >=0.3.9,<1
    - click >=8,<9
    - email-validator >=1.0.5
    - flask >=2,<3.0.0
    - flask-babel >=1,<3
    - flask-limiter >3,<4
    - flask-login >=0.3,<0.7
    - flask-sqlalchemy >=2.4,<3
    - flask-wtf >=0.14.2,<2
    - flask-jwt-extended >=4.0.0,<5.0.0
    - jsonschema >=3,<5
    - marshmallow >=3.18.0,<4
    - marshmallow-sqlalchemy >=0.22.0,<0.29.0
    - prison >=0.2.1,<1.0.0
    - pyjwt >=2.0.0,<3.0.0
    - python-dateutil >=2.3,<3
    - sqlalchemy <1.5
    - sqlalchemy-utils >=0.32.21,<1
    - wtforms <4
    - werkzeug <4

test:
  imports:
    - flask_appbuilder
    - flask_appbuilder.babel
    - flask_appbuilder.charts
    - flask_appbuilder.models
    - flask_appbuilder.models.generic
    - flask_appbuilder.models.mongoengine
    - flask_appbuilder.models.sqla
    - flask_appbuilder.security
    - flask_appbuilder.security.mongoengine
    - flask_appbuilder.security.sqla
    - flask_appbuilder.translations
  requires:
    - pip
  commands:
    - fabmanager --help
    - pip check

about:
  home: http://flaskappbuilder.pythonanywhere.com/
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Simple and rapid application development framework, built on top of Flask. includes detailed security, auto CRUD generation for your models, google charts and much more.
  dev_url: https://github.com/dpgaspar/flask-appbuilder/
  doc_url: https://github.com/dpgaspar/flask-appbuilder/

extra:
  recipe-maintainers:
    - halldc
    - xylar
