{% set name = "Flask-AppBuilder" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8934017c4dee955fbdd4da122406a14ae54380198f865fe451bfdfe95c9be09e

build:
  noarch: python
  entry_points:
    - fabmanager = flask_appbuilder.console:cli
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - apispec[yaml] >=1.1.1,<2
    - colorama >=0.3.9,<1
    - click >=6.7,<8
    - flask >=0.12,<2
    - flask-babel >=1,<2
    - flask-login >=0.3,<0.5
    - flask-openid >=1.2.5,<2
    - flask-sqlalchemy >=2.4,<3
    - flask-wtf >=0.14.2,<1
    - flask-jwt-extended >=3.18,<4
    - jsonschema >=3.0.1,<4
    - marshmallow >=2.18.0,<3.0.0
    - marshmallow-enum >=1.4.1,<2
    - marshmallow-sqlalchemy >=0.16.1,<1
    - prison >=0.1.2,<1.0.0
    - pyjwt >=1.7.1
    - python-dateutil >=2.3,<3
    - sqlalchemy-utils >=0.32.21,<1

test:
  imports:
    - flask_appbuilder
    - flask_appbuilder.babel
    - flask_appbuilder.charts
    - flask_appbuilder.models
    - flask_appbuilder.models.generic
    - flask_appbuilder.models.mongoengine
    - flask_appbuilder.models.sqla
    - flask_appbuilder.security
    - flask_appbuilder.security.mongoengine
    - flask_appbuilder.security.sqla
    - flask_appbuilder.tests
    - flask_appbuilder.translations

  commands:
    - fabmanager --help

about:
  home: http://flaskappbuilder.pythonanywhere.com/
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Simple and rapid application development framework, built on top of Flask. includes detailed security, auto CRUD generation for your models, google charts
    and much more.
  dev_url: https://github.com/dpgaspar/flask-appbuilder/
  doc_url: https://github.com/dpgaspar/flask-appbuilder/

extra:
  recipe-maintainers:
    - pmlandwehr
    - halldc
    - xylar
