{% set name = "Flask-AppBuilder" %}
{% set version = "1.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c0cb7035a867dbdbcab23877e321d115971c1b2e98f207ee3efcce1eb32cb064

build:
  noarch: python
  entry_points:
    - fabmanager = flask_appbuilder.console:cli
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - colorama ==0.3.9
    - click ==6.7
    - flask >=0.12.1,<0.12.99
    - flask-babel ==0.11.1
    - flask-login ==0.2.11
    - flask-openid ==1.2.5
    - flask-sqlalchemy ==2.1
    - flask-wtf ==0.14.2
    - python-dateutil >=2.3, <3

test:
  imports:
    - examples
    - flask_appbuilder
    - flask_appbuilder.babel
    - flask_appbuilder.charts
    - flask_appbuilder.models
    - flask_appbuilder.models.generic
    - flask_appbuilder.models.mongoengine
    - flask_appbuilder.models.sqla
    - flask_appbuilder.security
    - flask_appbuilder.security.mongoengine
    - flask_appbuilder.security.sqla
    - flask_appbuilder.tests
    - flask_appbuilder.translations

  commands:
    - fabmanager --help

about:
  home: http://flaskappbuilder.pythonanywhere.com/
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Simple and rapid application development framework, built on top of Flask. includes detailed security, auto CRUD generation for your models, google charts and much more.'
  dev_url: https://github.com/dpgaspar/flask-appbuilder/
  doc_url: https://github.com/dpgaspar/flask-appbuilder/

extra:
  recipe-maintainers:
    - pmlandwehr
    - halldc
