{% set name = "Flask-AppBuilder" %}
{% set version = "3.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: de53e5da250a3a64865ee0a2ed2f9235117d0206bf6f33bdfe3e3da6334bb0d1

build:
  noarch: python
  entry_points:
    - fabmanager = flask_appbuilder.console:cli
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - apispec >=3.3,<4
    - colorama >=0.3.9,<1
    - click >=6.7,<9
    - email_validator >=1.0.5,<2
    # an incompatibility with itsdangerous is fixed with later flask versions
    # - flask >=0.12,<2
    - flask >=1.1.4,<2
    - flask-babel >=1,<3
    - flask-login >=0.3,<0.5
    - flask-openid >=1.2.5,<2
    - flask-sqlalchemy >=2.4,<3
    - flask-wtf >=0.14.2,<0.15.0
    - flask-jwt-extended >=3.18,<4
    - jsonschema >=3,<5
    - marshmallow >=3,<4
    - marshmallow-enum >=1.5.1,<2
    - marshmallow-sqlalchemy >=0.22.0,<0.27.0
    - prison >=0.2.1,<1.0.0
    - pyjwt >=1.7.1,<2.0.0
    - python-dateutil >=2.3,<3
    - sqlalchemy <1.5.0
    - sqlalchemy-utils >=0.32.21,<1
    - wtforms <3.0.0

test:
  imports:
    - flask_appbuilder
    - flask_appbuilder.babel
    - flask_appbuilder.charts
    - flask_appbuilder.models
    - flask_appbuilder.models.generic
    - flask_appbuilder.models.mongoengine
    - flask_appbuilder.models.sqla
    - flask_appbuilder.security
    - flask_appbuilder.security.mongoengine
    - flask_appbuilder.security.sqla
    - flask_appbuilder.tests
    - flask_appbuilder.translations
  requires:
    - pip
  commands:
    - fabmanager --help
    - pip check

about:
  home: http://flaskappbuilder.pythonanywhere.com/
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Simple and rapid application development framework, built on top of Flask. includes detailed security, auto CRUD generation for your models, google charts and much more.
  dev_url: https://github.com/dpgaspar/flask-appbuilder/
  doc_url: https://github.com/dpgaspar/flask-appbuilder/

extra:
  recipe-maintainers:
    - halldc
    - xylar
