{% set name = "Flask-AppBuilder" %}
{% set version = "1.9.6" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "4c0b2eca7240060a70ee2a350056e3c4558ae4f6f70aedb415f62f4d28a7999e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  skip: True  # [py36]
  entry_points:
    - fabmanager = flask_appbuilder.console:cli
  
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - colorama ==0.3.9
    - click ==6.7
    - flask >=0.12.1,<0.12.99
    - flask-login >=0.2.11,<0.2.99
    - flask-sqlalchemy ==2.1
    - flask-openid ==1.2.5
    - flask-wtf ==0.14.2
    - flask-babel ==0.11.1
    - python-dateutil ==2.3


test:
  imports:
    - examples
    - flask_appbuilder
    - flask_appbuilder.babel
    - flask_appbuilder.charts
    - flask_appbuilder.models
    - flask_appbuilder.models.generic
    - flask_appbuilder.models.mongoengine
    - flask_appbuilder.models.sqla
    - flask_appbuilder.security
    - flask_appbuilder.security.mongoengine
    - flask_appbuilder.security.sqla
    - flask_appbuilder.tests
    - flask_appbuilder.translations

  commands:
    - fabmanager --help

about:
  home: http://flaskappbuilder.pythonanywhere.com/
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Simple and rapid application development framework, built on top of Flask. includes detailed security, auto CRUD generation for your models, google charts and much more.'
  dev_url: https://github.com/dpgaspar/flask-appbuilder/
  doc_url: https://github.com/dpgaspar/flask-appbuilder/

extra:
  recipe-maintainers:
    - pmlandwehr
