schema_version: 1

context:
  name: flask-appbuilder
  version: "5.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: a5f6f34aa4ae0092a9eeb5051dc210869d9360429a429b0be88416c2616e1281

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - apispec >=6.0.0,<7
    - colorama >=0.3.9,<1
    - click >=8,<9
    - email-validator >=1.0.5
    - flask >=2,<4
    - flask-babel >=3,<5
    - flask-limiter >3,<4
    - flask-login >=0.3,<0.7
    - flask-sqlalchemy >=2.4.0,<4
    - flask-wtf >=0.14.2,<2
    - flask-jwt-extended >=4.0.0,<5.0.0
    - jsonschema >=3,<5
    - marshmallow >=3.18.0,<5
    - marshmallow-sqlalchemy >=0.22.0,<3.0.0
    - prison >=0.2.1,<1.0.0
    - pyjwt >=2.0.0,<3.0.0
    - python-dateutil >=2.3,<3
    - sqlalchemy >=1.4.0,<3
    - sqlalchemy-utils >=0.32.21,<1
    - wtforms <4
    - werkzeug <4

tests:
  - python:
      imports:
        - flask_appbuilder
        - flask_appbuilder.babel
        - flask_appbuilder.charts
        - flask_appbuilder.models
        - flask_appbuilder.security
        - flask_appbuilder.translations
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  license_file: LICENSE
  license: BSD-3-Clause
  summary: Simple and rapid application development framework, built on top of Flask. includes detailed security, auto CRUD generation for your models, google charts and much more.
  homepage: http://flaskappbuilder.pythonanywhere.com/
  repository: https://github.com/dpgaspar/flask-appbuilder/
  documentation: https://github.com/dpgaspar/flask-appbuilder/

extra:
  recipe-maintainers:
    - halldc
    - xylar
