travis:
  secure:
    BINSTAR_TOKEN: R5XTB0IVqax9j/hjoncgOjlONdBDU+4OLeLHdqDkZO3M2zX3sxykYpBx2toBBdS8G63QhlX3qIpo0C4Eg7klyTH+kp89PWyUz/5RbYlKJc+RHU2dibrQpUsn4aW0OEOXdwm658hWOJ41Z4WnCeH80uqwhOjsTaLMR0zo51iYwBWeZG0fMmEcJnz74WSXKchU/ohODmPyCMto6QgLdABw6K/RGxXsT9jABvAnuJzAgBPeQASXhAQWiPoZarKNwrDDJUPfNU1rBaay7NScvHM0x03har9OvZmdLkD7z5QKbL9Xq8ArFyvO13+3jIyq6NLL9gUZ68lw04RBaRowlHTwRDHaKV42gP2EayuHcxNGzlIn7oiX0N1E/jj6CW3Sa2na1xAIGyQCMC/4UwPeWbqjpT/2fC5cUl1AzFDm6rJjYQdWaJz2AZEPFB3yR6o5uqLYcRd0lEgDmg41nNlCmdFyOOu2Qbze67fPZ5xQilX8e5Fhi+877AwiBpJfPtxeq0txJcwcaRQlS96LnjDnJKAXPWDGXFrAp4HRp+0mxxEz1LLFdfp48Rq6o8nB8taOi7RV3j81LXik3HS5xdwbeKwa/7ZjqPq3arjOQFOUfCfYo7WFThZd49i6QyvTSaNXK6tpTquQH3adgCEMW/UWRP1j+ubyFH6a7gQFpXFEwKaQuSw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
